---
management:
  port: 22443

server:
  port: 33443

auth:
  token: replaceMe!
  accountType: bot

messageGrabbing:
  enabled: true
  grabbers:
    - grabberName: firstName
      routes:
        - source: general
          destinations: links, links
    - grabberName: secondName
      routes:
        - source: general
          destinations: none
